version: "3"

tasks:
  dev:
    desc: Start the MCP server with hot-reload (HTTP mode)
    cmd: watchexec -r -e go,yaml -- go run ./cmd/mcp-server --config config.yaml --http :8888 --debug

  build:
    desc: Build the MCP server binary
    cmd: go build -o mcp-server ./cmd/mcp-server

  test:
    desc: Run tests
    cmd: go test ./...

  lint:
    desc: Run linter
    cmd: golangci-lint run

  tidy:
    desc: Tidy go modules
    cmd: go mod tidy

  generate:
    desc: Generate OpenAPI client bindings
    cmds:
      - rm -rf uptraceapi/
      - go get -tool github.com/yorunikakeru4/oapi-codegen-dd/v3/cmd/oapi-codegen@latest
      - go run github.com/yorunikakeru4/oapi-codegen-dd/v3/cmd/oapi-codegen -config oapi-codegen.yaml openapi/openapi.yaml
