package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/goccy/go-yaml"
)

type OpenAPISpec struct {
	Paths map[string]map[string]struct {
		OperationID string `yaml:"operationId"`
		Summary     string `yaml:"summary"`
		Description string `yaml:"description"`
	} `yaml:"paths"`
}

type operation struct {
	ID          string
	Summary     string
	Description string
}

var tmpl = template.Must(template.New("descriptions").Parse(`// Code generated by generate-descriptions; DO NOT EDIT.

package uptraceapi

// OperationDescription holds metadata for an API operation.
type OperationDescription struct {
	Summary     string
	Description string
}

// Operations maps operationId to its description from the OpenAPI spec.
var Operations = map[string]OperationDescription{
{{- range .}}
	{{printf "%q" .ID}}: {
		Summary:     {{printf "%q" .Summary}},
		Description: {{printf "%q" .Description}},
	},
{{- end}}
}
`))

func main() {
	data, err := os.ReadFile("openapi/openapi.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "reading spec: %v\n", err)
		os.Exit(1)
	}

	var spec OpenAPISpec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		fmt.Fprintf(os.Stderr, "parsing spec: %v\n", err)
		os.Exit(1)
	}

	var ops []operation
	for _, methods := range spec.Paths {
		for _, op := range methods {
			if op.OperationID == "" {
				continue
			}
			ops = append(ops, operation{
				ID:          op.OperationID,
				Summary:     op.Summary,
				Description: strings.TrimSpace(op.Description),
			})
		}
	}
	sort.Slice(ops, func(i, j int) bool {
		return ops[i].ID < ops[j].ID
	})

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ops); err != nil {
		fmt.Fprintf(os.Stderr, "executing template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "formatting: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("uptraceapi/descriptions.go", formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated uptraceapi/descriptions.go with %d operations\n", len(ops))
}
