// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/uptrace/oapi-codegen-dd/v3/pkg/runtime"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// CreateAnnotation Create annotation
	CreateAnnotation(ctx context.Context, options *CreateAnnotationRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// PublicListSpans List spans
	PublicListSpans(ctx context.Context, options *PublicListSpansRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PublicListSpansResponse, error)

	// PublicListSpanGroups List groups
	PublicListSpanGroups(ctx context.Context, options *PublicListSpanGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PublicListSpanGroupsResponse, error)

	// ListSpans List spans
	ListSpans(ctx context.Context, options *ListSpansRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListSpansResponse, error)

	// ListSpanGroups List groups
	ListSpanGroups(ctx context.Context, options *ListSpanGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListSpanGroupsResponse, error)

	// QueryTimeseries Timeseries
	QueryTimeseries(ctx context.Context, options *QueryTimeseriesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*QueryTimeseriesResponse, error)

	// QueryQuantiles Quantiles
	QueryQuantiles(ctx context.Context, options *QueryQuantilesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*QueryQuantilesResponse, error)

	// ListTraceGroups List trace groups
	ListTraceGroups(ctx context.Context, options *ListTraceGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListTraceGroupsResponse, error)

	// ListTraces List traces
	ListTraces(ctx context.Context, options *ListTracesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListTracesResponse, error)

	// SyncFixtures Sync fixtures
	SyncFixtures(ctx context.Context, options *SyncFixturesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// BindFixtureKeys Bind existing resources to fixture keys
	BindFixtureKeys(ctx context.Context, options *BindFixtureKeysRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// ListMonitors List monitors
	ListMonitors(ctx context.Context, options *ListMonitorsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMonitorsResponse, error)

	// CreateMonitor Create a monitor
	CreateMonitor(ctx context.Context, options *CreateMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateMonitorResponse, error)

	// GetMonitor Get a monitor
	GetMonitor(ctx context.Context, options *GetMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetMonitorResponse, error)

	// UpdateMonitor Update a monitor
	UpdateMonitor(ctx context.Context, options *UpdateMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateMonitorResponse, error)

	// DeleteMonitor Delete a monitor
	DeleteMonitor(ctx context.Context, options *DeleteMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// ListDashboards List dashboards
	ListDashboards(ctx context.Context, options *ListDashboardsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListDashboardsResponse, error)

	// ListDashboardTags List dashboard tags
	ListDashboardTags(ctx context.Context, options *ListDashboardTagsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListDashboardTagsResponse, error)

	// ExploreMetrics Explore metrics
	ExploreMetrics(ctx context.Context, options *ExploreMetricsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ExploreMetricsResponseJSON, error)

	// ListMetricAttributes List metric attributes
	ListMetricAttributes(ctx context.Context, options *ListMetricAttributesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMetricAttributesResponseJSON, error)

	// ListMetricAttributeValues List attribute values
	ListMetricAttributeValues(ctx context.Context, options *ListMetricAttributeValuesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMetricAttributeValuesResponseJSON, error)

	// CreateDashboardFromYAML Create dashboard from YAML
	CreateDashboardFromYAML(ctx context.Context, options *CreateDashboardFromYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateDashboardFromYAMLResponse, error)

	// GetDashboard Get a dashboard
	GetDashboard(ctx context.Context, options *GetDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetDashboardResponse, error)

	// DeleteDashboard Delete a dashboard
	DeleteDashboard(ctx context.Context, options *DeleteDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// GetDashboardYAML Get dashboard YAML
	GetDashboardYAML(ctx context.Context, options *GetDashboardYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetDashboardYAMLResponse, error)

	// UpdateDashboardFromYAML Update dashboard from YAML
	UpdateDashboardFromYAML(ctx context.Context, options *UpdateDashboardFromYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateDashboardFromYAMLResponse, error)

	// CloneDashboard Clone a dashboard
	CloneDashboard(ctx context.Context, options *CloneDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloneDashboardResponse, error)

	// ResetDashboard Reset a dashboard
	ResetDashboard(ctx context.Context, options *ResetDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// PinDashboard Pin a dashboard
	PinDashboard(ctx context.Context, options *PinDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// UnpinDashboard Unpin a dashboard
	UnpinDashboard(ctx context.Context, options *UnpinDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// UpdateDashboardTable Update dashboard table
	UpdateDashboardTable(ctx context.Context, options *UpdateDashboardTableRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// UpdateDashboardGrid Update dashboard grid query
	UpdateDashboardGrid(ctx context.Context, options *UpdateDashboardGridRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// CreateGridItem Create grid item
	CreateGridItem(ctx context.Context, options *CreateGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateGridItemResponse, error)

	// UpdateGridItem Update grid item
	UpdateGridItem(ctx context.Context, options *UpdateGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateGridItemResponse, error)

	// DeleteGridItem Delete grid item
	DeleteGridItem(ctx context.Context, options *DeleteGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DeleteGridItemResponse, error)

	// CreateGridRow Create grid row
	CreateGridRow(ctx context.Context, options *CreateGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateGridRowResponse, error)

	// UpdateGridRow Update grid row
	UpdateGridRow(ctx context.Context, options *UpdateGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateGridRowResponse, error)

	// DeleteGridRow Delete grid row
	DeleteGridRow(ctx context.Context, options *DeleteGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error)

	// MoveGridRowUp Move grid row up
	MoveGridRowUp(ctx context.Context, options *MoveGridRowUpRequestOptions, reqEditors ...runtime.RequestEditorFn) (*MoveGridRowUpResponse, error)

	// MoveGridRowDown Move grid row down
	MoveGridRowDown(ctx context.Context, options *MoveGridRowDownRequestOptions, reqEditors ...runtime.RequestEditorFn) (*MoveGridRowDownResponse, error)

	// ListNotificationChannels List notification channels
	ListNotificationChannels(ctx context.Context, options *ListNotificationChannelsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListNotificationChannelsResponse, error)

	// CreateNotificationChannel Create notification channel
	CreateNotificationChannel(ctx context.Context, options *CreateNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateNotificationChannelResponse, error)

	// GetNotificationChannel Get notification channel
	GetNotificationChannel(ctx context.Context, options *GetNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetNotificationChannelResponse, error)

	// UpdateNotificationChannel Update notification channel
	UpdateNotificationChannel(ctx context.Context, options *UpdateNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateNotificationChannelResponse, error)

	// DeleteNotificationChannel Delete notification channel
	DeleteNotificationChannel(ctx context.Context, options *DeleteNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DeleteNotificationChannelResponse, error)
}

// CreateAnnotation Create annotation
func (c *Client) CreateAnnotation(ctx context.Context, options *CreateAnnotationRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/api/v1/annotations",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateAnnotationErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/annotations")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// PublicListSpans List spans
func (c *Client) PublicListSpans(ctx context.Context, options *PublicListSpansRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PublicListSpansResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tracing/{project_id}/spans",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*PublicListSpansResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(PublicListSpansErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(PublicListSpansResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tracing/{project_id}/spans")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// PublicListSpanGroups List groups
func (c *Client) PublicListSpanGroups(ctx context.Context, options *PublicListSpanGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*PublicListSpanGroupsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tracing/{project_id}/groups",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*PublicListSpanGroupsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(PublicListSpanGroupsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(PublicListSpanGroupsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tracing/{project_id}/groups")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListSpans List spans
func (c *Client) ListSpans(ctx context.Context, options *ListSpansRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListSpansResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/spans",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListSpansResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListSpansErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListSpansResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/spans")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListSpanGroups List groups
func (c *Client) ListSpanGroups(ctx context.Context, options *ListSpanGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListSpanGroupsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/groups",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListSpanGroupsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListSpanGroupsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListSpanGroupsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/groups")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// QueryTimeseries Timeseries
func (c *Client) QueryTimeseries(ctx context.Context, options *QueryTimeseriesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*QueryTimeseriesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/timeseries",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*QueryTimeseriesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(QueryTimeseriesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(QueryTimeseriesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/timeseries")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// QueryQuantiles Quantiles
func (c *Client) QueryQuantiles(ctx context.Context, options *QueryQuantilesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*QueryQuantilesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/quantiles",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*QueryQuantilesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(QueryQuantilesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(QueryQuantilesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/quantiles")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListTraceGroups List trace groups
func (c *Client) ListTraceGroups(ctx context.Context, options *ListTraceGroupsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListTraceGroupsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/trace-groups",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListTraceGroupsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListTraceGroupsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListTraceGroupsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/trace-groups")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListTraces List traces
func (c *Client) ListTraces(ctx context.Context, options *ListTracesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListTracesResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/tracing/{project_id}/traces",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListTracesResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListTracesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListTracesResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/tracing/{project_id}/traces")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// SyncFixtures Sync fixtures
func (c *Client) SyncFixtures(ctx context.Context, options *SyncFixturesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/api/v1/fixtures",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(SyncFixturesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/fixtures")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// BindFixtureKeys Bind existing resources to fixture keys
func (c *Client) BindFixtureKeys(ctx context.Context, options *BindFixtureKeysRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/api/v1/fixtures/bindings",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(BindFixtureKeysErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/fixtures/bindings")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListMonitors List monitors
func (c *Client) ListMonitors(ctx context.Context, options *ListMonitorsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMonitorsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/monitors",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListMonitorsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListMonitorsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListMonitorsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/monitors")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateMonitor Create a monitor
func (c *Client) CreateMonitor(ctx context.Context, options *CreateMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateMonitorResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/monitors",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateMonitorResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateMonitorErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateMonitorResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/monitors")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetMonitor Get a monitor
func (c *Client) GetMonitor(ctx context.Context, options *GetMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetMonitorResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/monitors/{monitor_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetMonitorResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetMonitorErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetMonitorResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/monitors/{monitor_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateMonitor Update a monitor
func (c *Client) UpdateMonitor(ctx context.Context, options *UpdateMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateMonitorResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/monitors/{monitor_id}",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateMonitorResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateMonitorErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateMonitorResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/monitors/{monitor_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// DeleteMonitor Delete a monitor
func (c *Client) DeleteMonitor(ctx context.Context, options *DeleteMonitorRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/monitors/{monitor_id}",
		Method:     "DELETE",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(DeleteMonitorErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/monitors/{monitor_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListDashboards List dashboards
func (c *Client) ListDashboards(ctx context.Context, options *ListDashboardsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListDashboardsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListDashboardsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListDashboardsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListDashboardsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListDashboardTags List dashboard tags
func (c *Client) ListDashboardTags(ctx context.Context, options *ListDashboardTagsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListDashboardTagsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/tags",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListDashboardTagsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListDashboardTagsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListDashboardTagsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/tags")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ExploreMetrics Explore metrics
func (c *Client) ExploreMetrics(ctx context.Context, options *ExploreMetricsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ExploreMetricsResponseJSON, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/metrics/{project_id}/explore",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ExploreMetricsResponseJSON, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ExploreMetricsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ExploreMetricsResponseJSON)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/metrics/{project_id}/explore")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListMetricAttributes List metric attributes
func (c *Client) ListMetricAttributes(ctx context.Context, options *ListMetricAttributesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMetricAttributesResponseJSON, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/metrics/{project_id}/attributes",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListMetricAttributesResponseJSON, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListMetricAttributesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListMetricAttributesResponseJSON)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/metrics/{project_id}/attributes")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListMetricAttributeValues List attribute values
func (c *Client) ListMetricAttributeValues(ctx context.Context, options *ListMetricAttributeValuesRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListMetricAttributeValuesResponseJSON, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/metrics/{project_id}/attributes/{attr_key}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListMetricAttributeValuesResponseJSON, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListMetricAttributeValuesErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListMetricAttributeValuesResponseJSON)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/metrics/{project_id}/attributes/{attr_key}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateDashboardFromYAML Create dashboard from YAML
func (c *Client) CreateDashboardFromYAML(ctx context.Context, options *CreateDashboardFromYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateDashboardFromYAMLResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/yaml",
		Method:      "POST",
		Options:     options,
		ContentType: "text/yaml",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateDashboardFromYAMLResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateDashboardFromYAMLErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateDashboardFromYAMLResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/yaml")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetDashboard Get a dashboard
func (c *Client) GetDashboard(ctx context.Context, options *GetDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetDashboardResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetDashboardResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetDashboardResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// DeleteDashboard Delete a dashboard
func (c *Client) DeleteDashboard(ctx context.Context, options *DeleteDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}",
		Method:     "DELETE",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(DeleteDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetDashboardYAML Get dashboard YAML
func (c *Client) GetDashboardYAML(ctx context.Context, options *GetDashboardYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetDashboardYAMLResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/yaml",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetDashboardYAMLResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetDashboardYAMLErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		result := GetDashboardYAMLResponse(bodyBytes)
		return &result, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/yaml")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateDashboardFromYAML Update dashboard from YAML
func (c *Client) UpdateDashboardFromYAML(ctx context.Context, options *UpdateDashboardFromYAMLRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateDashboardFromYAMLResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/yaml",
		Method:      "PUT",
		Options:     options,
		ContentType: "text/yaml",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateDashboardFromYAMLResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateDashboardFromYAMLErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateDashboardFromYAMLResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/yaml")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CloneDashboard Clone a dashboard
func (c *Client) CloneDashboard(ctx context.Context, options *CloneDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloneDashboardResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/clone",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CloneDashboardResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CloneDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CloneDashboardResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/clone")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ResetDashboard Reset a dashboard
func (c *Client) ResetDashboard(ctx context.Context, options *ResetDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/reset",
		Method:     "PUT",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ResetDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/reset")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// PinDashboard Pin a dashboard
func (c *Client) PinDashboard(ctx context.Context, options *PinDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/pinned",
		Method:     "PUT",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(PinDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/pinned")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UnpinDashboard Unpin a dashboard
func (c *Client) UnpinDashboard(ctx context.Context, options *UnpinDashboardRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/unpinned",
		Method:     "PUT",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UnpinDashboardErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/unpinned")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateDashboardTable Update dashboard table
func (c *Client) UpdateDashboardTable(ctx context.Context, options *UpdateDashboardTableRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/table",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateDashboardTableErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/table")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateDashboardGrid Update dashboard grid query
func (c *Client) UpdateDashboardGrid(ctx context.Context, options *UpdateDashboardGridRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateDashboardGridErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateGridItem Create grid item
func (c *Client) CreateGridItem(ctx context.Context, options *CreateGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateGridItemResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateGridItemResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateGridItemErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateGridItemResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateGridItem Update grid item
func (c *Client) UpdateGridItem(ctx context.Context, options *UpdateGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateGridItemResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid/{grid_item_id}",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateGridItemResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateGridItemErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateGridItemResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid/{grid_item_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// DeleteGridItem Delete grid item
func (c *Client) DeleteGridItem(ctx context.Context, options *DeleteGridItemRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DeleteGridItemResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid/{grid_item_id}",
		Method:     "DELETE",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*DeleteGridItemResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(DeleteGridItemErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(DeleteGridItemResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/grid/{grid_item_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateGridRow Create grid row
func (c *Client) CreateGridRow(ctx context.Context, options *CreateGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateGridRowResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateGridRowResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateGridRowErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateGridRowResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateGridRow Update grid row
func (c *Client) UpdateGridRow(ctx context.Context, options *UpdateGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateGridRowResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateGridRowResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateGridRowErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateGridRowResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// DeleteGridRow Delete grid row
func (c *Client) DeleteGridRow(ctx context.Context, options *DeleteGridRowRequestOptions, reqEditors ...runtime.RequestEditorFn) (*struct{}, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}",
		Method:     "DELETE",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*struct{}, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(DeleteGridRowErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(struct{})
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// MoveGridRowUp Move grid row up
func (c *Client) MoveGridRowUp(ctx context.Context, options *MoveGridRowUpRequestOptions, reqEditors ...runtime.RequestEditorFn) (*MoveGridRowUpResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}/up",
		Method:     "PUT",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*MoveGridRowUpResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(MoveGridRowUpErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(MoveGridRowUpResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}/up")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// MoveGridRowDown Move grid row down
func (c *Client) MoveGridRowDown(ctx context.Context, options *MoveGridRowDownRequestOptions, reqEditors ...runtime.RequestEditorFn) (*MoveGridRowDownResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}/down",
		Method:     "PUT",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*MoveGridRowDownResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(MoveGridRowDownErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(MoveGridRowDownResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/dashboards/{dashboard_id}/rows/{row_id}/down")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ListNotificationChannels List notification channels
func (c *Client) ListNotificationChannels(ctx context.Context, options *ListNotificationChannelsRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ListNotificationChannelsResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/notification-channels",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ListNotificationChannelsResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(ListNotificationChannelsErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ListNotificationChannelsResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/notification-channels")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CreateNotificationChannel Create notification channel
func (c *Client) CreateNotificationChannel(ctx context.Context, options *CreateNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CreateNotificationChannelResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/notification-channels",
		Method:      "POST",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CreateNotificationChannelResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(CreateNotificationChannelErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CreateNotificationChannelResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/notification-channels")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetNotificationChannel Get notification channel
func (c *Client) GetNotificationChannel(ctx context.Context, options *GetNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetNotificationChannelResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/notification-channels/{channel_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetNotificationChannelResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(GetNotificationChannelErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetNotificationChannelResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/notification-channels/{channel_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UpdateNotificationChannel Update notification channel
func (c *Client) UpdateNotificationChannel(ctx context.Context, options *UpdateNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*UpdateNotificationChannelResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL:  c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/notification-channels/{channel_id}",
		Method:      "PUT",
		Options:     options,
		ContentType: "application/json",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UpdateNotificationChannelResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(UpdateNotificationChannelErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UpdateNotificationChannelResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/notification-channels/{channel_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// DeleteNotificationChannel Delete notification channel
func (c *Client) DeleteNotificationChannel(ctx context.Context, options *DeleteNotificationChannelRequestOptions, reqEditors ...runtime.RequestEditorFn) (*DeleteNotificationChannelResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/internal/v1/projects/{project_id}/notification-channels/{channel_id}",
		Method:     "DELETE",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*DeleteNotificationChannelResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			target := new(DeleteNotificationChannelErrorResponse)
			err = json.Unmarshal(bodyBytes, target)
			if err != nil {
				return nil, fmt.Errorf("error decoding response: %w", err)
			}

			if errTarget, ok := any(*target).(error); ok {
				return nil, runtime.NewClientAPIError(errTarget, runtime.WithStatusCode(resp.StatusCode))
			}
			return nil, runtime.NewClientAPIError(fmt.Errorf("API error (status %d): %v", resp.StatusCode, *target),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(DeleteNotificationChannelResponse)
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			err = fmt.Errorf("error decoding response: %w", err)
			return nil, err
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/internal/v1/projects/{project_id}/notification-channels/{channel_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)
