// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// CreateAnnotationRequestOptions is the options needed to make a request to CreateAnnotation.
type CreateAnnotationRequestOptions struct {
	Body *CreateAnnotationBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateAnnotationRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateAnnotationRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *CreateAnnotationRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateAnnotationRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateAnnotationRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ListSpansRequestOptions is the options needed to make a request to ListSpans.
type ListSpansRequestOptions struct {
	PathParams *ListSpansPath
	Query      *ListSpansQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ListSpansRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ListSpansRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ListSpansRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListSpansRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListSpansRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ListSpanGroupsRequestOptions is the options needed to make a request to ListSpanGroups.
type ListSpanGroupsRequestOptions struct {
	PathParams *ListSpanGroupsPath
	Query      *ListSpanGroupsQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ListSpanGroupsRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ListSpanGroupsRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ListSpanGroupsRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListSpanGroupsRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListSpanGroupsRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// SyncFixturesRequestOptions is the options needed to make a request to SyncFixtures.
type SyncFixturesRequestOptions struct {
	Body *SyncFixturesBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *SyncFixturesRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *SyncFixturesRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *SyncFixturesRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *SyncFixturesRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *SyncFixturesRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// BindFixtureKeysRequestOptions is the options needed to make a request to BindFixtureKeys.
type BindFixtureKeysRequestOptions struct {
	Body *BindFixtureKeysBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *BindFixtureKeysRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *BindFixtureKeysRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *BindFixtureKeysRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *BindFixtureKeysRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *BindFixtureKeysRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ListMonitorsRequestOptions is the options needed to make a request to ListMonitors.
type ListMonitorsRequestOptions struct {
	PathParams *ListMonitorsPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ListMonitorsRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ListMonitorsRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ListMonitorsRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListMonitorsRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListMonitorsRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateMonitorRequestOptions is the options needed to make a request to CreateMonitor.
type CreateMonitorRequestOptions struct {
	PathParams *CreateMonitorPath
	Body       *CreateMonitorBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateMonitorRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateMonitorRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CreateMonitorRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateMonitorRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateMonitorRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetMonitorRequestOptions is the options needed to make a request to GetMonitor.
type GetMonitorRequestOptions struct {
	PathParams *GetMonitorPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetMonitorRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetMonitorRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetMonitorRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetMonitorRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetMonitorRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateMonitorRequestOptions is the options needed to make a request to UpdateMonitor.
type UpdateMonitorRequestOptions struct {
	PathParams *UpdateMonitorPath
	Body       *UpdateMonitorBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateMonitorRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateMonitorRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateMonitorRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateMonitorRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateMonitorRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DeleteMonitorRequestOptions is the options needed to make a request to DeleteMonitor.
type DeleteMonitorRequestOptions struct {
	PathParams *DeleteMonitorPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *DeleteMonitorRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *DeleteMonitorRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *DeleteMonitorRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DeleteMonitorRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *DeleteMonitorRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ListDashboardsRequestOptions is the options needed to make a request to ListDashboards.
type ListDashboardsRequestOptions struct {
	PathParams *ListDashboardsPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ListDashboardsRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ListDashboardsRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ListDashboardsRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListDashboardsRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListDashboardsRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateDashboardFromYAMLRequestOptions is the options needed to make a request to CreateDashboardFromYAML.
type CreateDashboardFromYAMLRequestOptions struct {
	PathParams *CreateDashboardFromYAMLPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateDashboardFromYAMLRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateDashboardFromYAMLRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CreateDashboardFromYAMLRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateDashboardFromYAMLRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *CreateDashboardFromYAMLRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetDashboardRequestOptions is the options needed to make a request to GetDashboard.
type GetDashboardRequestOptions struct {
	PathParams *GetDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DeleteDashboardRequestOptions is the options needed to make a request to DeleteDashboard.
type DeleteDashboardRequestOptions struct {
	PathParams *DeleteDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *DeleteDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *DeleteDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *DeleteDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DeleteDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *DeleteDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetDashboardYAMLRequestOptions is the options needed to make a request to GetDashboardYAML.
type GetDashboardYAMLRequestOptions struct {
	PathParams *GetDashboardYAMLPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetDashboardYAMLRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetDashboardYAMLRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetDashboardYAMLRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetDashboardYAMLRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetDashboardYAMLRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateDashboardFromYAMLRequestOptions is the options needed to make a request to UpdateDashboardFromYAML.
type UpdateDashboardFromYAMLRequestOptions struct {
	PathParams *UpdateDashboardFromYAMLPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateDashboardFromYAMLRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateDashboardFromYAMLRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateDashboardFromYAMLRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateDashboardFromYAMLRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *UpdateDashboardFromYAMLRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CloneDashboardRequestOptions is the options needed to make a request to CloneDashboard.
type CloneDashboardRequestOptions struct {
	PathParams *CloneDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CloneDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CloneDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CloneDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CloneDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *CloneDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ResetDashboardRequestOptions is the options needed to make a request to ResetDashboard.
type ResetDashboardRequestOptions struct {
	PathParams *ResetDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ResetDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ResetDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ResetDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ResetDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ResetDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// PinDashboardRequestOptions is the options needed to make a request to PinDashboard.
type PinDashboardRequestOptions struct {
	PathParams *PinDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *PinDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *PinDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *PinDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *PinDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *PinDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UnpinDashboardRequestOptions is the options needed to make a request to UnpinDashboard.
type UnpinDashboardRequestOptions struct {
	PathParams *UnpinDashboardPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UnpinDashboardRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UnpinDashboardRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UnpinDashboardRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UnpinDashboardRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *UnpinDashboardRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateDashboardTableRequestOptions is the options needed to make a request to UpdateDashboardTable.
type UpdateDashboardTableRequestOptions struct {
	PathParams *UpdateDashboardTablePath
	Body       *UpdateDashboardTableBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateDashboardTableRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateDashboardTableRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateDashboardTableRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateDashboardTableRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateDashboardTableRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateDashboardGridRequestOptions is the options needed to make a request to UpdateDashboardGrid.
type UpdateDashboardGridRequestOptions struct {
	PathParams *UpdateDashboardGridPath
	Body       *UpdateDashboardGridBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateDashboardGridRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateDashboardGridRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateDashboardGridRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateDashboardGridRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateDashboardGridRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateGridItemRequestOptions is the options needed to make a request to CreateGridItem.
type CreateGridItemRequestOptions struct {
	PathParams *CreateGridItemPath
	Body       *CreateGridItemBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateGridItemRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateGridItemRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CreateGridItemRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateGridItemRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateGridItemRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateGridItemRequestOptions is the options needed to make a request to UpdateGridItem.
type UpdateGridItemRequestOptions struct {
	PathParams *UpdateGridItemPath
	Body       *UpdateGridItemBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateGridItemRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateGridItemRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateGridItemRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateGridItemRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateGridItemRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DeleteGridItemRequestOptions is the options needed to make a request to DeleteGridItem.
type DeleteGridItemRequestOptions struct {
	PathParams *DeleteGridItemPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *DeleteGridItemRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *DeleteGridItemRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *DeleteGridItemRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DeleteGridItemRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *DeleteGridItemRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateGridRowRequestOptions is the options needed to make a request to CreateGridRow.
type CreateGridRowRequestOptions struct {
	PathParams *CreateGridRowPath
	Body       *CreateGridRowBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateGridRowRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateGridRowRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CreateGridRowRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateGridRowRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateGridRowRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateGridRowRequestOptions is the options needed to make a request to UpdateGridRow.
type UpdateGridRowRequestOptions struct {
	PathParams *UpdateGridRowPath
	Body       *UpdateGridRowBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateGridRowRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateGridRowRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateGridRowRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateGridRowRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateGridRowRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DeleteGridRowRequestOptions is the options needed to make a request to DeleteGridRow.
type DeleteGridRowRequestOptions struct {
	PathParams *DeleteGridRowPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *DeleteGridRowRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *DeleteGridRowRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *DeleteGridRowRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DeleteGridRowRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *DeleteGridRowRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// MoveGridRowUpRequestOptions is the options needed to make a request to MoveGridRowUp.
type MoveGridRowUpRequestOptions struct {
	PathParams *MoveGridRowUpPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *MoveGridRowUpRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *MoveGridRowUpRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *MoveGridRowUpRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *MoveGridRowUpRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *MoveGridRowUpRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// MoveGridRowDownRequestOptions is the options needed to make a request to MoveGridRowDown.
type MoveGridRowDownRequestOptions struct {
	PathParams *MoveGridRowDownPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *MoveGridRowDownRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *MoveGridRowDownRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *MoveGridRowDownRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *MoveGridRowDownRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *MoveGridRowDownRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ListNotificationChannelsRequestOptions is the options needed to make a request to ListNotificationChannels.
type ListNotificationChannelsRequestOptions struct {
	PathParams *ListNotificationChannelsPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ListNotificationChannelsRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ListNotificationChannelsRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ListNotificationChannelsRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ListNotificationChannelsRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ListNotificationChannelsRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CreateNotificationChannelRequestOptions is the options needed to make a request to CreateNotificationChannel.
type CreateNotificationChannelRequestOptions struct {
	PathParams *CreateNotificationChannelPath
	Body       *CreateNotificationChannelBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CreateNotificationChannelRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CreateNotificationChannelRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CreateNotificationChannelRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CreateNotificationChannelRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *CreateNotificationChannelRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetNotificationChannelRequestOptions is the options needed to make a request to GetNotificationChannel.
type GetNotificationChannelRequestOptions struct {
	PathParams *GetNotificationChannelPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetNotificationChannelRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetNotificationChannelRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetNotificationChannelRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetNotificationChannelRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetNotificationChannelRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// UpdateNotificationChannelRequestOptions is the options needed to make a request to UpdateNotificationChannel.
type UpdateNotificationChannelRequestOptions struct {
	PathParams *UpdateNotificationChannelPath
	Body       *UpdateNotificationChannelBody
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *UpdateNotificationChannelRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *UpdateNotificationChannelRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *UpdateNotificationChannelRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *UpdateNotificationChannelRequestOptions) GetBody() any {
	return o.Body
}

// GetHeader returns the headers as a map.
func (o *UpdateNotificationChannelRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// DeleteNotificationChannelRequestOptions is the options needed to make a request to DeleteNotificationChannel.
type DeleteNotificationChannelRequestOptions struct {
	PathParams *DeleteNotificationChannelPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *DeleteNotificationChannelRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *DeleteNotificationChannelRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *DeleteNotificationChannelRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *DeleteNotificationChannelRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *DeleteNotificationChannelRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}
