// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type OrgUserFixtureRole string

const (
	Admin           OrgUserFixtureRole = "admin"
	BillingManager  OrgUserFixtureRole = "billing_manager"
	BillingManager1 OrgUserFixtureRole = "billing-manager"
	Collaborator    OrgUserFixtureRole = "collaborator"
	Member          OrgUserFixtureRole = "member"
	Owner           OrgUserFixtureRole = "owner"
	Viewer          OrgUserFixtureRole = "viewer"
)

// Validate checks if the OrgUserFixtureRole value is valid
func (o OrgUserFixtureRole) Validate() error {
	switch o {
	case Admin, BillingManager, BillingManager1, Collaborator, Member, Owner, Viewer:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OrgUserFixtureRole value, got: %v", o))
	}
}

type ProjectUserFixturePermLevel string

const (
	Maintain                         ProjectUserFixturePermLevel = "maintain"
	None                             ProjectUserFixturePermLevel = "none"
	ProjectUserFixturePermLevelAdmin ProjectUserFixturePermLevel = "admin"
	View                             ProjectUserFixturePermLevel = "view"
)

// Validate checks if the ProjectUserFixturePermLevel value is valid
func (p ProjectUserFixturePermLevel) Validate() error {
	switch p {
	case Maintain, None, ProjectUserFixturePermLevelAdmin, View:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProjectUserFixturePermLevel value, got: %v", p))
	}
}

type MetricMonitorRequestType string

const (
	Metric MetricMonitorRequestType = "metric"
)

// Validate checks if the MetricMonitorRequestType value is valid
func (m MetricMonitorRequestType) Validate() error {
	switch m {
	case Metric:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MetricMonitorRequestType value, got: %v", m))
	}
}

type ErrorMonitorRequestType string

const (
	ErrorMonitorRequestTypeError ErrorMonitorRequestType = "error"
)

// Validate checks if the ErrorMonitorRequestType value is valid
func (e ErrorMonitorRequestType) Validate() error {
	switch e {
	case ErrorMonitorRequestTypeError:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ErrorMonitorRequestType value, got: %v", e))
	}
}

type MetricMonitorParamsBoundsSource string

const (
	Auto   MetricMonitorParamsBoundsSource = "auto"
	Manual MetricMonitorParamsBoundsSource = "manual"
)

// Validate checks if the MetricMonitorParamsBoundsSource value is valid
func (m MetricMonitorParamsBoundsSource) Validate() error {
	switch m {
	case Auto, Manual:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MetricMonitorParamsBoundsSource value, got: %v", m))
	}
}

type MetricMonitorParamsTolerance string

const (
	High   MetricMonitorParamsTolerance = "high"
	Low    MetricMonitorParamsTolerance = "low"
	Medium MetricMonitorParamsTolerance = "medium"
)

// Validate checks if the MetricMonitorParamsTolerance value is valid
func (m MetricMonitorParamsTolerance) Validate() error {
	switch m {
	case High, Low, Medium:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MetricMonitorParamsTolerance value, got: %v", m))
	}
}

type MetricMonitorParamsNullsMode string

const (
	Allow   MetricMonitorParamsNullsMode = "allow"
	Convert MetricMonitorParamsNullsMode = "convert"
	Forbid  MetricMonitorParamsNullsMode = "forbid"
)

// Validate checks if the MetricMonitorParamsNullsMode value is valid
func (m MetricMonitorParamsNullsMode) Validate() error {
	switch m {
	case Allow, Convert, Forbid:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MetricMonitorParamsNullsMode value, got: %v", m))
	}
}

type DefaultRepeatIntervalStrategy string

const (
	Default DefaultRepeatIntervalStrategy = "default"
)

// Validate checks if the DefaultRepeatIntervalStrategy value is valid
func (d DefaultRepeatIntervalStrategy) Validate() error {
	switch d {
	case Default:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DefaultRepeatIntervalStrategy value, got: %v", d))
	}
}

type FixedRepeatIntervalStrategy string

const (
	Fixed FixedRepeatIntervalStrategy = "fixed"
)

// Validate checks if the FixedRepeatIntervalStrategy value is valid
func (f FixedRepeatIntervalStrategy) Validate() error {
	switch f {
	case Fixed:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid FixedRepeatIntervalStrategy value, got: %v", f))
	}
}

type LinearRepeatIntervalStrategy string

const (
	Linear LinearRepeatIntervalStrategy = "linear"
)

// Validate checks if the LinearRepeatIntervalStrategy value is valid
func (l LinearRepeatIntervalStrategy) Validate() error {
	switch l {
	case Linear:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid LinearRepeatIntervalStrategy value, got: %v", l))
	}
}

type ExponentialRepeatIntervalStrategy string

const (
	Exponential ExponentialRepeatIntervalStrategy = "exponential"
)

// Validate checks if the ExponentialRepeatIntervalStrategy value is valid
func (e ExponentialRepeatIntervalStrategy) Validate() error {
	switch e {
	case Exponential:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ExponentialRepeatIntervalStrategy value, got: %v", e))
	}
}

type MonitorType string

const (
	MonitorTypeError  MonitorType = "error"
	MonitorTypeMetric MonitorType = "metric"
)

// Validate checks if the MonitorType value is valid
func (m MonitorType) Validate() error {
	switch m {
	case MonitorTypeError, MonitorTypeMetric:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MonitorType value, got: %v", m))
	}
}

type MonitorStatus string

const (
	Active   MonitorStatus = "active"
	Disabled MonitorStatus = "disabled"
	Firing   MonitorStatus = "firing"
	NoData   MonitorStatus = "no_data"
	Paused   MonitorStatus = "paused"
)

// Validate checks if the MonitorStatus value is valid
func (m MonitorStatus) Validate() error {
	switch m {
	case Active, Disabled, Firing, NoData, Paused:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid MonitorStatus value, got: %v", m))
	}
}

type TableColumnAggFunc string

const (
	Avg     TableColumnAggFunc = "avg"
	AvgZero TableColumnAggFunc = "avg_zero"
	Last    TableColumnAggFunc = "last"
	Max     TableColumnAggFunc = "max"
	Median  TableColumnAggFunc = "median"
	Min     TableColumnAggFunc = "min"
	Sum     TableColumnAggFunc = "sum"
)

// Validate checks if the TableColumnAggFunc value is valid
func (t TableColumnAggFunc) Validate() error {
	switch t {
	case Avg, AvgZero, Last, Max, Median, Min, Sum:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid TableColumnAggFunc value, got: %v", t))
	}
}

type GridItemDashKind string

const (
	Grid  GridItemDashKind = "grid"
	Table GridItemDashKind = "table"
)

// Validate checks if the GridItemDashKind value is valid
func (g GridItemDashKind) Validate() error {
	switch g {
	case Grid, Table:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GridItemDashKind value, got: %v", g))
	}
}

type GridItemType string

const (
	Chart             GridItemType = "chart"
	Gauge             GridItemType = "gauge"
	GridItemTypeTable GridItemType = "table"
	Heatmap           GridItemType = "heatmap"
)

// Validate checks if the GridItemType value is valid
func (g GridItemType) Validate() error {
	switch g {
	case Chart, Gauge, GridItemTypeTable, Heatmap:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GridItemType value, got: %v", g))
	}
}

type GridItemRequestDashKind string

const (
	GridItemRequestDashKindGrid  GridItemRequestDashKind = "grid"
	GridItemRequestDashKindTable GridItemRequestDashKind = "table"
)

// Validate checks if the GridItemRequestDashKind value is valid
func (g GridItemRequestDashKind) Validate() error {
	switch g {
	case GridItemRequestDashKindGrid, GridItemRequestDashKindTable:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GridItemRequestDashKind value, got: %v", g))
	}
}

type GridItemRequestType string

const (
	GridItemRequestTypeChart   GridItemRequestType = "chart"
	GridItemRequestTypeGauge   GridItemRequestType = "gauge"
	GridItemRequestTypeHeatmap GridItemRequestType = "heatmap"
	GridItemRequestTypeTable   GridItemRequestType = "table"
)

// Validate checks if the GridItemRequestType value is valid
func (g GridItemRequestType) Validate() error {
	switch g {
	case GridItemRequestTypeChart, GridItemRequestTypeGauge, GridItemRequestTypeHeatmap, GridItemRequestTypeTable:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GridItemRequestType value, got: %v", g))
	}
}

type SlackParamsAuthMethod string

const (
	Token   SlackParamsAuthMethod = "token"
	Webhook SlackParamsAuthMethod = "webhook"
)

// Validate checks if the SlackParamsAuthMethod value is valid
func (s SlackParamsAuthMethod) Validate() error {
	switch s {
	case Token, Webhook:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid SlackParamsAuthMethod value, got: %v", s))
	}
}

type PagerdutyParamsSeverity string

const (
	Critical                     PagerdutyParamsSeverity = "critical"
	Info                         PagerdutyParamsSeverity = "info"
	PagerdutyParamsSeverityError PagerdutyParamsSeverity = "error"
	Warning                      PagerdutyParamsSeverity = "warning"
)

// Validate checks if the PagerdutyParamsSeverity value is valid
func (p PagerdutyParamsSeverity) Validate() error {
	switch p {
	case Critical, Info, PagerdutyParamsSeverityError, Warning:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid PagerdutyParamsSeverity value, got: %v", p))
	}
}

type ServicenowParamsImpact string

const (
	N1 ServicenowParamsImpact = "1"
	N2 ServicenowParamsImpact = "2"
	N3 ServicenowParamsImpact = "3"
)

// Validate checks if the ServicenowParamsImpact value is valid
func (s ServicenowParamsImpact) Validate() error {
	switch s {
	case N1, N2, N3:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ServicenowParamsImpact value, got: %v", s))
	}
}

type ServicenowParamsUrgency string

const (
	ServicenowParamsUrgencyN1 ServicenowParamsUrgency = "1"
	ServicenowParamsUrgencyN2 ServicenowParamsUrgency = "2"
	ServicenowParamsUrgencyN3 ServicenowParamsUrgency = "3"
)

// Validate checks if the ServicenowParamsUrgency value is valid
func (s ServicenowParamsUrgency) Validate() error {
	switch s {
	case ServicenowParamsUrgencyN1, ServicenowParamsUrgencyN2, ServicenowParamsUrgencyN3:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ServicenowParamsUrgency value, got: %v", s))
	}
}

type ServicenowParamsSeverity string

const (
	N4                         ServicenowParamsSeverity = "4"
	N5                         ServicenowParamsSeverity = "5"
	ServicenowParamsSeverityN1 ServicenowParamsSeverity = "1"
	ServicenowParamsSeverityN2 ServicenowParamsSeverity = "2"
	ServicenowParamsSeverityN3 ServicenowParamsSeverity = "3"
)

// Validate checks if the ServicenowParamsSeverity value is valid
func (s ServicenowParamsSeverity) Validate() error {
	switch s {
	case N4, N5, ServicenowParamsSeverityN1, ServicenowParamsSeverityN2, ServicenowParamsSeverityN3:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ServicenowParamsSeverity value, got: %v", s))
	}
}

type ServicenowParamsNotify string

const (
	ServicenowParamsNotifyN1 ServicenowParamsNotify = "1"
	ServicenowParamsNotifyN2 ServicenowParamsNotify = "2"
)

// Validate checks if the ServicenowParamsNotify value is valid
func (s ServicenowParamsNotify) Validate() error {
	switch s {
	case ServicenowParamsNotifyN1, ServicenowParamsNotifyN2:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ServicenowParamsNotify value, got: %v", s))
	}
}

type OpsgenieParamsPriority string

const (
	P1 OpsgenieParamsPriority = "P1"
	P2 OpsgenieParamsPriority = "P2"
	P3 OpsgenieParamsPriority = "P3"
	P4 OpsgenieParamsPriority = "P4"
	P5 OpsgenieParamsPriority = "P5"
)

// Validate checks if the OpsgenieParamsPriority value is valid
func (o OpsgenieParamsPriority) Validate() error {
	switch o {
	case P1, P2, P3, P4, P5:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OpsgenieParamsPriority value, got: %v", o))
	}
}

type NotificationChannelType string

const (
	Alertmanager                   NotificationChannelType = "alertmanager"
	GoogleChat                     NotificationChannelType = "google_chat"
	Mattermost                     NotificationChannelType = "mattermost"
	NotificationChannelTypeWebhook NotificationChannelType = "webhook"
	Opsgenie                       NotificationChannelType = "opsgenie"
	Pagerduty                      NotificationChannelType = "pagerduty"
	Servicenow                     NotificationChannelType = "servicenow"
	Slack                          NotificationChannelType = "slack"
	Teams                          NotificationChannelType = "teams"
	Telegram                       NotificationChannelType = "telegram"
)

// Validate checks if the NotificationChannelType value is valid
func (n NotificationChannelType) Validate() error {
	switch n {
	case Alertmanager, GoogleChat, Mattermost, NotificationChannelTypeWebhook, Opsgenie, Pagerduty, Servicenow, Slack, Teams, Telegram:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NotificationChannelType value, got: %v", n))
	}
}

type NotificationChannelStatus string

const (
	Delivering                        NotificationChannelStatus = "delivering"
	Draft                             NotificationChannelStatus = "draft"
	NotificationChannelStatusDisabled NotificationChannelStatus = "disabled"
	NotificationChannelStatusPaused   NotificationChannelStatus = "paused"
)

// Validate checks if the NotificationChannelStatus value is valid
func (n NotificationChannelStatus) Validate() error {
	switch n {
	case Delivering, Draft, NotificationChannelStatusDisabled, NotificationChannelStatusPaused:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NotificationChannelStatus value, got: %v", n))
	}
}

type NotificationChannelPriorities string

const (
	NotificationChannelPrioritiesHigh   NotificationChannelPriorities = "high"
	NotificationChannelPrioritiesInfo   NotificationChannelPriorities = "info"
	NotificationChannelPrioritiesLow    NotificationChannelPriorities = "low"
	NotificationChannelPrioritiesMedium NotificationChannelPriorities = "medium"
)

// Validate checks if the NotificationChannelPriorities value is valid
func (n NotificationChannelPriorities) Validate() error {
	switch n {
	case NotificationChannelPrioritiesHigh, NotificationChannelPrioritiesInfo, NotificationChannelPrioritiesLow, NotificationChannelPrioritiesMedium:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NotificationChannelPriorities value, got: %v", n))
	}
}

type NotificationChannelRequestType string

const (
	NotificationChannelRequestTypeAlertmanager NotificationChannelRequestType = "alertmanager"
	NotificationChannelRequestTypeGoogleChat   NotificationChannelRequestType = "google_chat"
	NotificationChannelRequestTypeMattermost   NotificationChannelRequestType = "mattermost"
	NotificationChannelRequestTypeOpsgenie     NotificationChannelRequestType = "opsgenie"
	NotificationChannelRequestTypePagerduty    NotificationChannelRequestType = "pagerduty"
	NotificationChannelRequestTypeServicenow   NotificationChannelRequestType = "servicenow"
	NotificationChannelRequestTypeSlack        NotificationChannelRequestType = "slack"
	NotificationChannelRequestTypeTeams        NotificationChannelRequestType = "teams"
	NotificationChannelRequestTypeTelegram     NotificationChannelRequestType = "telegram"
	NotificationChannelRequestTypeWebhook      NotificationChannelRequestType = "webhook"
)

// Validate checks if the NotificationChannelRequestType value is valid
func (n NotificationChannelRequestType) Validate() error {
	switch n {
	case NotificationChannelRequestTypeAlertmanager, NotificationChannelRequestTypeGoogleChat, NotificationChannelRequestTypeMattermost, NotificationChannelRequestTypeOpsgenie, NotificationChannelRequestTypePagerduty, NotificationChannelRequestTypeServicenow, NotificationChannelRequestTypeSlack, NotificationChannelRequestTypeTeams, NotificationChannelRequestTypeTelegram, NotificationChannelRequestTypeWebhook:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NotificationChannelRequestType value, got: %v", n))
	}
}

type NotificationChannelRequestPriorities string

const (
	NotificationChannelRequestPrioritiesHigh   NotificationChannelRequestPriorities = "high"
	NotificationChannelRequestPrioritiesInfo   NotificationChannelRequestPriorities = "info"
	NotificationChannelRequestPrioritiesLow    NotificationChannelRequestPriorities = "low"
	NotificationChannelRequestPrioritiesMedium NotificationChannelRequestPriorities = "medium"
)

// Validate checks if the NotificationChannelRequestPriorities value is valid
func (n NotificationChannelRequestPriorities) Validate() error {
	switch n {
	case NotificationChannelRequestPrioritiesHigh, NotificationChannelRequestPrioritiesInfo, NotificationChannelRequestPrioritiesLow, NotificationChannelRequestPrioritiesMedium:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NotificationChannelRequestPriorities value, got: %v", n))
	}
}
