// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

type ProjectID = int64

type MonitorID = int64

type DashboardID = int64

type ChannelID = int64

type GridItemID = int64

type RowID = int64

type ListSpansPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type ListSpanGroupsPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type ListMonitorsPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type CreateMonitorPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type GetMonitorPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// MonitorID Monitor ID.
	MonitorID MonitorID `json:"monitor_id" jsonschema:"Monitor ID." validate:"required"`
}

func (g GetMonitorPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UpdateMonitorPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// MonitorID Monitor ID.
	MonitorID MonitorID `json:"monitor_id" jsonschema:"Monitor ID." validate:"required"`
}

func (u UpdateMonitorPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeleteMonitorPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// MonitorID Monitor ID.
	MonitorID MonitorID `json:"monitor_id" jsonschema:"Monitor ID." validate:"required"`
}

func (d DeleteMonitorPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type ListDashboardsPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type CreateDashboardFromYAMLPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type GetDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (g GetDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type DeleteDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (d DeleteDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GetDashboardYAMLPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (g GetDashboardYAMLPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UpdateDashboardFromYAMLPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (u UpdateDashboardFromYAMLPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type CloneDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (c CloneDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ResetDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (r ResetDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type PinDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (p PinDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type UnpinDashboardPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (u UnpinDashboardPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type UpdateDashboardTablePath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (u UpdateDashboardTablePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type UpdateDashboardGridPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (u UpdateDashboardGridPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type CreateGridItemPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (c CreateGridItemPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type UpdateGridItemPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// GridItemID Grid item ID.
	GridItemID GridItemID `json:"grid_item_id" jsonschema:"Grid item ID." validate:"required"`
}

func (u UpdateGridItemPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeleteGridItemPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// GridItemID Grid item ID.
	GridItemID GridItemID `json:"grid_item_id" jsonschema:"Grid item ID." validate:"required"`
}

func (d DeleteGridItemPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type CreateGridRowPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`
}

func (c CreateGridRowPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type UpdateGridRowPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// RowID Grid row ID.
	RowID RowID `json:"row_id" jsonschema:"Grid row ID." validate:"required"`
}

func (u UpdateGridRowPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeleteGridRowPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// RowID Grid row ID.
	RowID RowID `json:"row_id" jsonschema:"Grid row ID." validate:"required"`
}

func (d DeleteGridRowPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type MoveGridRowUpPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// RowID Grid row ID.
	RowID RowID `json:"row_id" jsonschema:"Grid row ID." validate:"required"`
}

func (m MoveGridRowUpPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type MoveGridRowDownPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// DashboardID Dashboard ID.
	DashboardID DashboardID `json:"dashboard_id" jsonschema:"Dashboard ID." validate:"required"`

	// RowID Grid row ID.
	RowID RowID `json:"row_id" jsonschema:"Grid row ID." validate:"required"`
}

func (m MoveGridRowDownPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type ListNotificationChannelsPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type CreateNotificationChannelPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`
}

type GetNotificationChannelPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// ChannelID Notification channel ID.
	ChannelID ChannelID `json:"channel_id" jsonschema:"Notification channel ID." validate:"required"`
}

func (g GetNotificationChannelPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UpdateNotificationChannelPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// ChannelID Notification channel ID.
	ChannelID ChannelID `json:"channel_id" jsonschema:"Notification channel ID." validate:"required"`
}

func (u UpdateNotificationChannelPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeleteNotificationChannelPath struct {
	// ProjectID Uptrace project ID.
	ProjectID *ProjectID `json:"project_id,omitempty" jsonschema:"Uptrace project ID."`

	// ChannelID Notification channel ID.
	ChannelID ChannelID `json:"channel_id" jsonschema:"Notification channel ID." validate:"required"`
}

func (d DeleteNotificationChannelPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}
