// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type CreateAnnotationBody = AnnotationCreateRequest

// SyncFixturesBody Fixture data used to create, update, or delete resources by key.
type SyncFixturesBody = SeedDataRequest

// BindFixtureKeysBody Links existing resources to fixture keys.
type BindFixtureKeysBody = LinkDataRequest

type CreateMonitorBody struct {
	CreateMonitorBody_OneOf *CreateMonitorBody_OneOf `json:"-"`
}

func (c CreateMonitorBody) Validate() error {
	var errors runtime.ValidationErrors
	if c.CreateMonitorBody_OneOf != nil {
		if v, ok := any(c.CreateMonitorBody_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("CreateMonitorBody_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (c CreateMonitorBody) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(c.CreateMonitorBody_OneOf)
		if err != nil {
			return nil, fmt.Errorf("CreateMonitorBody_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (c *CreateMonitorBody) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if c.CreateMonitorBody_OneOf == nil {
		c.CreateMonitorBody_OneOf = &CreateMonitorBody_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, c.CreateMonitorBody_OneOf); err != nil {
		return fmt.Errorf("CreateMonitorBody_OneOf unmarshal: %w", err)
	}

	return nil
}

type UpdateMonitorBody struct {
	UpdateMonitorBody_OneOf *UpdateMonitorBody_OneOf `json:"-"`
}

func (u UpdateMonitorBody) Validate() error {
	var errors runtime.ValidationErrors
	if u.UpdateMonitorBody_OneOf != nil {
		if v, ok := any(u.UpdateMonitorBody_OneOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("UpdateMonitorBody_OneOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (u UpdateMonitorBody) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(u.UpdateMonitorBody_OneOf)
		if err != nil {
			return nil, fmt.Errorf("UpdateMonitorBody_OneOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (u *UpdateMonitorBody) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if u.UpdateMonitorBody_OneOf == nil {
		u.UpdateMonitorBody_OneOf = &UpdateMonitorBody_OneOf{}
	}

	if err := runtime.UnmarshalJSON(data, u.UpdateMonitorBody_OneOf); err != nil {
		return fmt.Errorf("UpdateMonitorBody_OneOf unmarshal: %w", err)
	}

	return nil
}

type UpdateDashboardTableBody = DashboardTableUpdate

type UpdateDashboardGridBody struct {
	GridQuery *string `json:"gridQuery,omitempty"`
}

type CreateGridItemBody = GridItemRequest

type UpdateGridItemBody = GridItemRequest

type CreateGridRowBody = GridRowRequest

type UpdateGridRowBody = GridRow

type CreateNotificationChannelBody = NotificationChannelRequest

type UpdateNotificationChannelBody = NotificationChannelRequest
