// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"time"

	"github.com/yorunikakeru4/oapi-codegen-dd/v3/pkg/runtime"
)

// TimeStart RFC3339 timestamp.
type TimeStart = time.Time

// TimeEnd RFC3339 timestamp.
type TimeEnd = time.Time

type Limit = int32

type ListSpansQuery struct {
	// TimeStart Start time as RFC3339 timestamp.
	TimeStart TimeStart `json:"time_start" jsonschema:"Start time as RFC3339 timestamp." validate:"required"`

	// TimeEnd End time as RFC3339 timestamp.
	TimeEnd TimeEnd `json:"time_end" jsonschema:"End time as RFC3339 timestamp." validate:"required"`

	// TraceID Filter spans by trace ID.
	TraceID *string `json:"trace_id,omitempty" jsonschema:"Filter spans by trace ID."`

	// ID Filter spans by span ID.
	ID *int `json:"id,omitempty" jsonschema:"Filter spans by span ID."`

	// ParentID Filter spans by parent span ID.
	ParentID *int `json:"parent_id,omitempty" jsonschema:"Filter spans by parent span ID."`

	// Limit Limit number of results.
	Limit *Limit `json:"limit,omitempty" jsonschema:"Limit number of results."`
}

func (l ListSpansQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(l))
}

type ListSpanGroupsQuery struct {
	// TimeStart Start time as RFC3339 timestamp.
	TimeStart TimeStart `json:"time_start" jsonschema:"Start time as RFC3339 timestamp." validate:"required"`

	// TimeEnd End time as RFC3339 timestamp.
	TimeEnd TimeEnd `json:"time_end" jsonschema:"End time as RFC3339 timestamp." validate:"required"`

	// Query Aggregate spans using the specified query.
	Query *string `json:"query,omitempty" jsonschema:"Aggregate spans using the specified query."`

	// Limit Limit number of results.
	Limit *Limit `json:"limit,omitempty" jsonschema:"Limit number of results."`

	// Search Search for spans containing option1 or option2.
	Search *string `json:"search,omitempty" jsonschema:"Search for spans containing option1 or option2."`

	// DurationGte Duration greater than or equal to N (microseconds).
	DurationGte *int64 `json:"duration_gte,omitempty" jsonschema:"Duration greater than or equal to N (microseconds)."`

	// DurationLt Duration less than N (microseconds).
	DurationLt *int64 `json:"duration_lt,omitempty" jsonschema:"Duration less than N (microseconds)."`
}

func (l ListSpanGroupsQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(l))
}
