// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

type BadRequest = Error

type Unauthorized = Error

type Forbidden = Error

type NotFound = Error

type InternalError = Error

type CreateAnnotationErrorResponse = BadRequest

type ListSpansResponse map[string]any

type ListSpansErrorResponse = BadRequest

type ListSpanGroupsResponse map[string]any

type ListSpanGroupsErrorResponse = BadRequest

type SyncFixturesErrorResponse = BadRequest

type BindFixtureKeysErrorResponse = BadRequest

type ListMonitorsResponse struct {
	Monitors []Monitor `json:"monitors" validate:"required"`
}

type ListMonitorsErrorResponse = BadRequest

type CreateMonitorResponse = MonitorResponse

type CreateMonitorErrorResponse = BadRequest

type GetMonitorResponse = MonitorResponse

type GetMonitorErrorResponse = BadRequest

type UpdateMonitorResponse = MonitorResponse

type UpdateMonitorErrorResponse = BadRequest

type DeleteMonitorErrorResponse = BadRequest

type ListDashboardsResponse struct {
	Dashboards []Dashboard `json:"dashboards" validate:"required"`
}

type ListDashboardsErrorResponse = BadRequest

type CreateDashboardFromYAMLResponse = DashboardResponse

type CreateDashboardFromYAMLErrorResponse = BadRequest

type GetDashboardResponse struct {
	Dashboard   Dashboard  `json:"dashboard"`
	TableItems  []GridItem `json:"tableItems,omitempty"`
	GridRows    []GridRow  `json:"gridRows,omitempty"`
	GridMetrics []string   `json:"gridMetrics,omitempty"`
	YamlURL     *string    `json:"yamlUrl,omitempty"`
}

type GetDashboardErrorResponse = BadRequest

type DeleteDashboardErrorResponse = BadRequest

type GetDashboardYAMLResponse = string

type GetDashboardYAMLErrorResponse = BadRequest

type UpdateDashboardFromYAMLResponse = DashboardResponse

type UpdateDashboardFromYAMLErrorResponse = BadRequest

type CloneDashboardResponse = DashboardResponse

type CloneDashboardErrorResponse = BadRequest

type ResetDashboardErrorResponse = BadRequest

type PinDashboardErrorResponse = BadRequest

type UnpinDashboardErrorResponse = BadRequest

type UpdateDashboardTableErrorResponse = BadRequest

type UpdateDashboardGridErrorResponse = BadRequest

type CreateGridItemResponse = GridItemResponse

type CreateGridItemErrorResponse = BadRequest

type UpdateGridItemResponse = GridItemResponse

type UpdateGridItemErrorResponse = BadRequest

type DeleteGridItemResponse = GridItemResponse

type DeleteGridItemErrorResponse = BadRequest

type CreateGridRowResponse = GridRowResponse

type CreateGridRowErrorResponse = BadRequest

type UpdateGridRowResponse = GridRowResponse

type UpdateGridRowErrorResponse = BadRequest

type DeleteGridRowErrorResponse = BadRequest

type MoveGridRowUpResponse = GridRowResponse

type MoveGridRowUpErrorResponse = BadRequest

type MoveGridRowDownResponse = GridRowResponse

type MoveGridRowDownErrorResponse = BadRequest

type ListNotificationChannelsResponse struct {
	Channels []NotificationChannel `json:"channels" validate:"required"`
}

type ListNotificationChannelsErrorResponse = BadRequest

type CreateNotificationChannelResponse = NotificationChannelResponse

type CreateNotificationChannelErrorResponse = BadRequest

type GetNotificationChannelResponse = NotificationChannelResponse

type GetNotificationChannelErrorResponse = BadRequest

type UpdateNotificationChannelResponse = NotificationChannelResponse

type UpdateNotificationChannelErrorResponse = BadRequest

type DeleteNotificationChannelResponse = NotificationChannelResponse

type DeleteNotificationChannelErrorResponse = BadRequest
