// Code generated by oapi-codegen. DO NOT EDIT.

package uptraceapi

import (
	"encoding/json"

	"github.com/uptrace/oapi-codegen-dd/v3/pkg/runtime"
)

type RepeatInterval_OneOf struct {
	union json.RawMessage
}

func (r *RepeatInterval_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the RepeatInterval_OneOf as bytes
func (r *RepeatInterval_OneOf) Raw() json.RawMessage {
	return r.union
}

// AsDefaultRepeatInterval returns the union data inside the RepeatInterval_OneOf as a DefaultRepeatInterval
func (r *RepeatInterval_OneOf) AsDefaultRepeatInterval() (DefaultRepeatInterval, error) {
	return runtime.UnmarshalAs[DefaultRepeatInterval](r.union)
}

// AsValidatedDefaultRepeatInterval returns the union data inside the RepeatInterval_OneOf as a validated DefaultRepeatInterval
func (r *RepeatInterval_OneOf) AsValidatedDefaultRepeatInterval() (DefaultRepeatInterval, error) {
	val, err := r.AsDefaultRepeatInterval()
	if err != nil {
		var zero DefaultRepeatInterval
		return zero, err
	}
	if err := r.validateDefaultRepeatInterval(val); err != nil {
		var zero DefaultRepeatInterval
		return zero, err
	}
	return val, nil
}

// FromDefaultRepeatInterval overwrites any union data inside the RepeatInterval_OneOf as the provided DefaultRepeatInterval
func (r *RepeatInterval_OneOf) FromDefaultRepeatInterval(val DefaultRepeatInterval) error {
	// Validate before storing
	if err := r.validateDefaultRepeatInterval(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	r.union = bts
	return err
}

// AsFixedRepeatInterval returns the union data inside the RepeatInterval_OneOf as a FixedRepeatInterval
func (r *RepeatInterval_OneOf) AsFixedRepeatInterval() (FixedRepeatInterval, error) {
	return runtime.UnmarshalAs[FixedRepeatInterval](r.union)
}

// AsValidatedFixedRepeatInterval returns the union data inside the RepeatInterval_OneOf as a validated FixedRepeatInterval
func (r *RepeatInterval_OneOf) AsValidatedFixedRepeatInterval() (FixedRepeatInterval, error) {
	val, err := r.AsFixedRepeatInterval()
	if err != nil {
		var zero FixedRepeatInterval
		return zero, err
	}
	if err := r.validateFixedRepeatInterval(val); err != nil {
		var zero FixedRepeatInterval
		return zero, err
	}
	return val, nil
}

// FromFixedRepeatInterval overwrites any union data inside the RepeatInterval_OneOf as the provided FixedRepeatInterval
func (r *RepeatInterval_OneOf) FromFixedRepeatInterval(val FixedRepeatInterval) error {
	// Validate before storing
	if err := r.validateFixedRepeatInterval(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	r.union = bts
	return err
}

// AsLinearRepeatInterval returns the union data inside the RepeatInterval_OneOf as a LinearRepeatInterval
func (r *RepeatInterval_OneOf) AsLinearRepeatInterval() (LinearRepeatInterval, error) {
	return runtime.UnmarshalAs[LinearRepeatInterval](r.union)
}

// AsValidatedLinearRepeatInterval returns the union data inside the RepeatInterval_OneOf as a validated LinearRepeatInterval
func (r *RepeatInterval_OneOf) AsValidatedLinearRepeatInterval() (LinearRepeatInterval, error) {
	val, err := r.AsLinearRepeatInterval()
	if err != nil {
		var zero LinearRepeatInterval
		return zero, err
	}
	if err := r.validateLinearRepeatInterval(val); err != nil {
		var zero LinearRepeatInterval
		return zero, err
	}
	return val, nil
}

// FromLinearRepeatInterval overwrites any union data inside the RepeatInterval_OneOf as the provided LinearRepeatInterval
func (r *RepeatInterval_OneOf) FromLinearRepeatInterval(val LinearRepeatInterval) error {
	// Validate before storing
	if err := r.validateLinearRepeatInterval(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	r.union = bts
	return err
}

// AsExponentialRepeatInterval returns the union data inside the RepeatInterval_OneOf as a ExponentialRepeatInterval
func (r *RepeatInterval_OneOf) AsExponentialRepeatInterval() (ExponentialRepeatInterval, error) {
	return runtime.UnmarshalAs[ExponentialRepeatInterval](r.union)
}

// AsValidatedExponentialRepeatInterval returns the union data inside the RepeatInterval_OneOf as a validated ExponentialRepeatInterval
func (r *RepeatInterval_OneOf) AsValidatedExponentialRepeatInterval() (ExponentialRepeatInterval, error) {
	val, err := r.AsExponentialRepeatInterval()
	if err != nil {
		var zero ExponentialRepeatInterval
		return zero, err
	}
	if err := r.validateExponentialRepeatInterval(val); err != nil {
		var zero ExponentialRepeatInterval
		return zero, err
	}
	return val, nil
}

// FromExponentialRepeatInterval overwrites any union data inside the RepeatInterval_OneOf as the provided ExponentialRepeatInterval
func (r *RepeatInterval_OneOf) FromExponentialRepeatInterval(val ExponentialRepeatInterval) error {
	// Validate before storing
	if err := r.validateExponentialRepeatInterval(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	r.union = bts
	return err
}

// validateDefaultRepeatInterval validates a DefaultRepeatInterval value
func (r *RepeatInterval_OneOf) validateDefaultRepeatInterval(val DefaultRepeatInterval) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateFixedRepeatInterval validates a FixedRepeatInterval value
func (r *RepeatInterval_OneOf) validateFixedRepeatInterval(val FixedRepeatInterval) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateLinearRepeatInterval validates a LinearRepeatInterval value
func (r *RepeatInterval_OneOf) validateLinearRepeatInterval(val LinearRepeatInterval) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateExponentialRepeatInterval validates a ExponentialRepeatInterval value
func (r *RepeatInterval_OneOf) validateExponentialRepeatInterval(val ExponentialRepeatInterval) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (r RepeatInterval_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := r.union.MarshalJSON()

	return bts, err
}

func (r *RepeatInterval_OneOf) UnmarshalJSON(bts []byte) error {
	err := r.union.UnmarshalJSON(bts)

	return err
}

type NotificationChannel_Params_OneOf struct {
	union json.RawMessage
}

func (n *NotificationChannel_Params_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the NotificationChannel_Params_OneOf as bytes
func (n *NotificationChannel_Params_OneOf) Raw() json.RawMessage {
	return n.union
}

// AsSlackParams returns the union data inside the NotificationChannel_Params_OneOf as a SlackParams
func (n *NotificationChannel_Params_OneOf) AsSlackParams() (SlackParams, error) {
	return runtime.UnmarshalAs[SlackParams](n.union)
}

// AsValidatedSlackParams returns the union data inside the NotificationChannel_Params_OneOf as a validated SlackParams
func (n *NotificationChannel_Params_OneOf) AsValidatedSlackParams() (SlackParams, error) {
	val, err := n.AsSlackParams()
	if err != nil {
		var zero SlackParams
		return zero, err
	}
	if err := n.validateSlackParams(val); err != nil {
		var zero SlackParams
		return zero, err
	}
	return val, nil
}

// FromSlackParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided SlackParams
func (n *NotificationChannel_Params_OneOf) FromSlackParams(val SlackParams) error {
	// Validate before storing
	if err := n.validateSlackParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsGoogleChatParams returns the union data inside the NotificationChannel_Params_OneOf as a GoogleChatParams
func (n *NotificationChannel_Params_OneOf) AsGoogleChatParams() (GoogleChatParams, error) {
	return runtime.UnmarshalAs[GoogleChatParams](n.union)
}

// AsValidatedGoogleChatParams returns the union data inside the NotificationChannel_Params_OneOf as a validated GoogleChatParams
func (n *NotificationChannel_Params_OneOf) AsValidatedGoogleChatParams() (GoogleChatParams, error) {
	val, err := n.AsGoogleChatParams()
	if err != nil {
		var zero GoogleChatParams
		return zero, err
	}
	if err := n.validateGoogleChatParams(val); err != nil {
		var zero GoogleChatParams
		return zero, err
	}
	return val, nil
}

// FromGoogleChatParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided GoogleChatParams
func (n *NotificationChannel_Params_OneOf) FromGoogleChatParams(val GoogleChatParams) error {
	// Validate before storing
	if err := n.validateGoogleChatParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsMattermostParams returns the union data inside the NotificationChannel_Params_OneOf as a MattermostParams
func (n *NotificationChannel_Params_OneOf) AsMattermostParams() (MattermostParams, error) {
	return runtime.UnmarshalAs[MattermostParams](n.union)
}

// AsValidatedMattermostParams returns the union data inside the NotificationChannel_Params_OneOf as a validated MattermostParams
func (n *NotificationChannel_Params_OneOf) AsValidatedMattermostParams() (MattermostParams, error) {
	val, err := n.AsMattermostParams()
	if err != nil {
		var zero MattermostParams
		return zero, err
	}
	if err := n.validateMattermostParams(val); err != nil {
		var zero MattermostParams
		return zero, err
	}
	return val, nil
}

// FromMattermostParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided MattermostParams
func (n *NotificationChannel_Params_OneOf) FromMattermostParams(val MattermostParams) error {
	// Validate before storing
	if err := n.validateMattermostParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsPagerdutyParams returns the union data inside the NotificationChannel_Params_OneOf as a PagerdutyParams
func (n *NotificationChannel_Params_OneOf) AsPagerdutyParams() (PagerdutyParams, error) {
	return runtime.UnmarshalAs[PagerdutyParams](n.union)
}

// AsValidatedPagerdutyParams returns the union data inside the NotificationChannel_Params_OneOf as a validated PagerdutyParams
func (n *NotificationChannel_Params_OneOf) AsValidatedPagerdutyParams() (PagerdutyParams, error) {
	val, err := n.AsPagerdutyParams()
	if err != nil {
		var zero PagerdutyParams
		return zero, err
	}
	if err := n.validatePagerdutyParams(val); err != nil {
		var zero PagerdutyParams
		return zero, err
	}
	return val, nil
}

// FromPagerdutyParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided PagerdutyParams
func (n *NotificationChannel_Params_OneOf) FromPagerdutyParams(val PagerdutyParams) error {
	// Validate before storing
	if err := n.validatePagerdutyParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsServicenowParams returns the union data inside the NotificationChannel_Params_OneOf as a ServicenowParams
func (n *NotificationChannel_Params_OneOf) AsServicenowParams() (ServicenowParams, error) {
	return runtime.UnmarshalAs[ServicenowParams](n.union)
}

// AsValidatedServicenowParams returns the union data inside the NotificationChannel_Params_OneOf as a validated ServicenowParams
func (n *NotificationChannel_Params_OneOf) AsValidatedServicenowParams() (ServicenowParams, error) {
	val, err := n.AsServicenowParams()
	if err != nil {
		var zero ServicenowParams
		return zero, err
	}
	if err := n.validateServicenowParams(val); err != nil {
		var zero ServicenowParams
		return zero, err
	}
	return val, nil
}

// FromServicenowParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided ServicenowParams
func (n *NotificationChannel_Params_OneOf) FromServicenowParams(val ServicenowParams) error {
	// Validate before storing
	if err := n.validateServicenowParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsOpsgenieParams returns the union data inside the NotificationChannel_Params_OneOf as a OpsgenieParams
func (n *NotificationChannel_Params_OneOf) AsOpsgenieParams() (OpsgenieParams, error) {
	return runtime.UnmarshalAs[OpsgenieParams](n.union)
}

// AsValidatedOpsgenieParams returns the union data inside the NotificationChannel_Params_OneOf as a validated OpsgenieParams
func (n *NotificationChannel_Params_OneOf) AsValidatedOpsgenieParams() (OpsgenieParams, error) {
	val, err := n.AsOpsgenieParams()
	if err != nil {
		var zero OpsgenieParams
		return zero, err
	}
	if err := n.validateOpsgenieParams(val); err != nil {
		var zero OpsgenieParams
		return zero, err
	}
	return val, nil
}

// FromOpsgenieParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided OpsgenieParams
func (n *NotificationChannel_Params_OneOf) FromOpsgenieParams(val OpsgenieParams) error {
	// Validate before storing
	if err := n.validateOpsgenieParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsTelegramParams returns the union data inside the NotificationChannel_Params_OneOf as a TelegramParams
func (n *NotificationChannel_Params_OneOf) AsTelegramParams() (TelegramParams, error) {
	return runtime.UnmarshalAs[TelegramParams](n.union)
}

// AsValidatedTelegramParams returns the union data inside the NotificationChannel_Params_OneOf as a validated TelegramParams
func (n *NotificationChannel_Params_OneOf) AsValidatedTelegramParams() (TelegramParams, error) {
	val, err := n.AsTelegramParams()
	if err != nil {
		var zero TelegramParams
		return zero, err
	}
	if err := n.validateTelegramParams(val); err != nil {
		var zero TelegramParams
		return zero, err
	}
	return val, nil
}

// FromTelegramParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided TelegramParams
func (n *NotificationChannel_Params_OneOf) FromTelegramParams(val TelegramParams) error {
	// Validate before storing
	if err := n.validateTelegramParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsTeamsParams returns the union data inside the NotificationChannel_Params_OneOf as a TeamsParams
func (n *NotificationChannel_Params_OneOf) AsTeamsParams() (TeamsParams, error) {
	return runtime.UnmarshalAs[TeamsParams](n.union)
}

// AsValidatedTeamsParams returns the union data inside the NotificationChannel_Params_OneOf as a validated TeamsParams
func (n *NotificationChannel_Params_OneOf) AsValidatedTeamsParams() (TeamsParams, error) {
	val, err := n.AsTeamsParams()
	if err != nil {
		var zero TeamsParams
		return zero, err
	}
	if err := n.validateTeamsParams(val); err != nil {
		var zero TeamsParams
		return zero, err
	}
	return val, nil
}

// FromTeamsParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided TeamsParams
func (n *NotificationChannel_Params_OneOf) FromTeamsParams(val TeamsParams) error {
	// Validate before storing
	if err := n.validateTeamsParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsWebhookParams returns the union data inside the NotificationChannel_Params_OneOf as a WebhookParams
func (n *NotificationChannel_Params_OneOf) AsWebhookParams() (WebhookParams, error) {
	return runtime.UnmarshalAs[WebhookParams](n.union)
}

// AsValidatedWebhookParams returns the union data inside the NotificationChannel_Params_OneOf as a validated WebhookParams
func (n *NotificationChannel_Params_OneOf) AsValidatedWebhookParams() (WebhookParams, error) {
	val, err := n.AsWebhookParams()
	if err != nil {
		var zero WebhookParams
		return zero, err
	}
	if err := n.validateWebhookParams(val); err != nil {
		var zero WebhookParams
		return zero, err
	}
	return val, nil
}

// FromWebhookParams overwrites any union data inside the NotificationChannel_Params_OneOf as the provided WebhookParams
func (n *NotificationChannel_Params_OneOf) FromWebhookParams(val WebhookParams) error {
	// Validate before storing
	if err := n.validateWebhookParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// validateSlackParams validates a SlackParams value
func (n *NotificationChannel_Params_OneOf) validateSlackParams(val SlackParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGoogleChatParams validates a GoogleChatParams value
func (n *NotificationChannel_Params_OneOf) validateGoogleChatParams(val GoogleChatParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateMattermostParams validates a MattermostParams value
func (n *NotificationChannel_Params_OneOf) validateMattermostParams(val MattermostParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePagerdutyParams validates a PagerdutyParams value
func (n *NotificationChannel_Params_OneOf) validatePagerdutyParams(val PagerdutyParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateServicenowParams validates a ServicenowParams value
func (n *NotificationChannel_Params_OneOf) validateServicenowParams(val ServicenowParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateOpsgenieParams validates a OpsgenieParams value
func (n *NotificationChannel_Params_OneOf) validateOpsgenieParams(val OpsgenieParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTelegramParams validates a TelegramParams value
func (n *NotificationChannel_Params_OneOf) validateTelegramParams(val TelegramParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTeamsParams validates a TeamsParams value
func (n *NotificationChannel_Params_OneOf) validateTeamsParams(val TeamsParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateWebhookParams validates a WebhookParams value
func (n *NotificationChannel_Params_OneOf) validateWebhookParams(val WebhookParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (n NotificationChannel_Params_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := n.union.MarshalJSON()

	return bts, err
}

func (n *NotificationChannel_Params_OneOf) UnmarshalJSON(bts []byte) error {
	err := n.union.UnmarshalJSON(bts)

	return err
}

type NotificationChannelRequest_Params_OneOf struct {
	union json.RawMessage
}

func (n *NotificationChannelRequest_Params_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the NotificationChannelRequest_Params_OneOf as bytes
func (n *NotificationChannelRequest_Params_OneOf) Raw() json.RawMessage {
	return n.union
}

// AsSlackParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a SlackParams
func (n *NotificationChannelRequest_Params_OneOf) AsSlackParams() (SlackParams, error) {
	return runtime.UnmarshalAs[SlackParams](n.union)
}

// AsValidatedSlackParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated SlackParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedSlackParams() (SlackParams, error) {
	val, err := n.AsSlackParams()
	if err != nil {
		var zero SlackParams
		return zero, err
	}
	if err := n.validateSlackParams(val); err != nil {
		var zero SlackParams
		return zero, err
	}
	return val, nil
}

// FromSlackParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided SlackParams
func (n *NotificationChannelRequest_Params_OneOf) FromSlackParams(val SlackParams) error {
	// Validate before storing
	if err := n.validateSlackParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsGoogleChatParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a GoogleChatParams
func (n *NotificationChannelRequest_Params_OneOf) AsGoogleChatParams() (GoogleChatParams, error) {
	return runtime.UnmarshalAs[GoogleChatParams](n.union)
}

// AsValidatedGoogleChatParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated GoogleChatParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedGoogleChatParams() (GoogleChatParams, error) {
	val, err := n.AsGoogleChatParams()
	if err != nil {
		var zero GoogleChatParams
		return zero, err
	}
	if err := n.validateGoogleChatParams(val); err != nil {
		var zero GoogleChatParams
		return zero, err
	}
	return val, nil
}

// FromGoogleChatParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided GoogleChatParams
func (n *NotificationChannelRequest_Params_OneOf) FromGoogleChatParams(val GoogleChatParams) error {
	// Validate before storing
	if err := n.validateGoogleChatParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsMattermostParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a MattermostParams
func (n *NotificationChannelRequest_Params_OneOf) AsMattermostParams() (MattermostParams, error) {
	return runtime.UnmarshalAs[MattermostParams](n.union)
}

// AsValidatedMattermostParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated MattermostParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedMattermostParams() (MattermostParams, error) {
	val, err := n.AsMattermostParams()
	if err != nil {
		var zero MattermostParams
		return zero, err
	}
	if err := n.validateMattermostParams(val); err != nil {
		var zero MattermostParams
		return zero, err
	}
	return val, nil
}

// FromMattermostParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided MattermostParams
func (n *NotificationChannelRequest_Params_OneOf) FromMattermostParams(val MattermostParams) error {
	// Validate before storing
	if err := n.validateMattermostParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsPagerdutyParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a PagerdutyParams
func (n *NotificationChannelRequest_Params_OneOf) AsPagerdutyParams() (PagerdutyParams, error) {
	return runtime.UnmarshalAs[PagerdutyParams](n.union)
}

// AsValidatedPagerdutyParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated PagerdutyParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedPagerdutyParams() (PagerdutyParams, error) {
	val, err := n.AsPagerdutyParams()
	if err != nil {
		var zero PagerdutyParams
		return zero, err
	}
	if err := n.validatePagerdutyParams(val); err != nil {
		var zero PagerdutyParams
		return zero, err
	}
	return val, nil
}

// FromPagerdutyParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided PagerdutyParams
func (n *NotificationChannelRequest_Params_OneOf) FromPagerdutyParams(val PagerdutyParams) error {
	// Validate before storing
	if err := n.validatePagerdutyParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsServicenowParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a ServicenowParams
func (n *NotificationChannelRequest_Params_OneOf) AsServicenowParams() (ServicenowParams, error) {
	return runtime.UnmarshalAs[ServicenowParams](n.union)
}

// AsValidatedServicenowParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated ServicenowParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedServicenowParams() (ServicenowParams, error) {
	val, err := n.AsServicenowParams()
	if err != nil {
		var zero ServicenowParams
		return zero, err
	}
	if err := n.validateServicenowParams(val); err != nil {
		var zero ServicenowParams
		return zero, err
	}
	return val, nil
}

// FromServicenowParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided ServicenowParams
func (n *NotificationChannelRequest_Params_OneOf) FromServicenowParams(val ServicenowParams) error {
	// Validate before storing
	if err := n.validateServicenowParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsOpsgenieParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a OpsgenieParams
func (n *NotificationChannelRequest_Params_OneOf) AsOpsgenieParams() (OpsgenieParams, error) {
	return runtime.UnmarshalAs[OpsgenieParams](n.union)
}

// AsValidatedOpsgenieParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated OpsgenieParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedOpsgenieParams() (OpsgenieParams, error) {
	val, err := n.AsOpsgenieParams()
	if err != nil {
		var zero OpsgenieParams
		return zero, err
	}
	if err := n.validateOpsgenieParams(val); err != nil {
		var zero OpsgenieParams
		return zero, err
	}
	return val, nil
}

// FromOpsgenieParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided OpsgenieParams
func (n *NotificationChannelRequest_Params_OneOf) FromOpsgenieParams(val OpsgenieParams) error {
	// Validate before storing
	if err := n.validateOpsgenieParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsTelegramParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a TelegramParams
func (n *NotificationChannelRequest_Params_OneOf) AsTelegramParams() (TelegramParams, error) {
	return runtime.UnmarshalAs[TelegramParams](n.union)
}

// AsValidatedTelegramParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated TelegramParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedTelegramParams() (TelegramParams, error) {
	val, err := n.AsTelegramParams()
	if err != nil {
		var zero TelegramParams
		return zero, err
	}
	if err := n.validateTelegramParams(val); err != nil {
		var zero TelegramParams
		return zero, err
	}
	return val, nil
}

// FromTelegramParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided TelegramParams
func (n *NotificationChannelRequest_Params_OneOf) FromTelegramParams(val TelegramParams) error {
	// Validate before storing
	if err := n.validateTelegramParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsTeamsParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a TeamsParams
func (n *NotificationChannelRequest_Params_OneOf) AsTeamsParams() (TeamsParams, error) {
	return runtime.UnmarshalAs[TeamsParams](n.union)
}

// AsValidatedTeamsParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated TeamsParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedTeamsParams() (TeamsParams, error) {
	val, err := n.AsTeamsParams()
	if err != nil {
		var zero TeamsParams
		return zero, err
	}
	if err := n.validateTeamsParams(val); err != nil {
		var zero TeamsParams
		return zero, err
	}
	return val, nil
}

// FromTeamsParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided TeamsParams
func (n *NotificationChannelRequest_Params_OneOf) FromTeamsParams(val TeamsParams) error {
	// Validate before storing
	if err := n.validateTeamsParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// AsWebhookParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a WebhookParams
func (n *NotificationChannelRequest_Params_OneOf) AsWebhookParams() (WebhookParams, error) {
	return runtime.UnmarshalAs[WebhookParams](n.union)
}

// AsValidatedWebhookParams returns the union data inside the NotificationChannelRequest_Params_OneOf as a validated WebhookParams
func (n *NotificationChannelRequest_Params_OneOf) AsValidatedWebhookParams() (WebhookParams, error) {
	val, err := n.AsWebhookParams()
	if err != nil {
		var zero WebhookParams
		return zero, err
	}
	if err := n.validateWebhookParams(val); err != nil {
		var zero WebhookParams
		return zero, err
	}
	return val, nil
}

// FromWebhookParams overwrites any union data inside the NotificationChannelRequest_Params_OneOf as the provided WebhookParams
func (n *NotificationChannelRequest_Params_OneOf) FromWebhookParams(val WebhookParams) error {
	// Validate before storing
	if err := n.validateWebhookParams(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	n.union = bts
	return err
}

// validateSlackParams validates a SlackParams value
func (n *NotificationChannelRequest_Params_OneOf) validateSlackParams(val SlackParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGoogleChatParams validates a GoogleChatParams value
func (n *NotificationChannelRequest_Params_OneOf) validateGoogleChatParams(val GoogleChatParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateMattermostParams validates a MattermostParams value
func (n *NotificationChannelRequest_Params_OneOf) validateMattermostParams(val MattermostParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePagerdutyParams validates a PagerdutyParams value
func (n *NotificationChannelRequest_Params_OneOf) validatePagerdutyParams(val PagerdutyParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateServicenowParams validates a ServicenowParams value
func (n *NotificationChannelRequest_Params_OneOf) validateServicenowParams(val ServicenowParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateOpsgenieParams validates a OpsgenieParams value
func (n *NotificationChannelRequest_Params_OneOf) validateOpsgenieParams(val OpsgenieParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTelegramParams validates a TelegramParams value
func (n *NotificationChannelRequest_Params_OneOf) validateTelegramParams(val TelegramParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTeamsParams validates a TeamsParams value
func (n *NotificationChannelRequest_Params_OneOf) validateTeamsParams(val TeamsParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateWebhookParams validates a WebhookParams value
func (n *NotificationChannelRequest_Params_OneOf) validateWebhookParams(val WebhookParams) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (n NotificationChannelRequest_Params_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := n.union.MarshalJSON()

	return bts, err
}

func (n *NotificationChannelRequest_Params_OneOf) UnmarshalJSON(bts []byte) error {
	err := n.union.UnmarshalJSON(bts)

	return err
}

type CreateMonitorBody_OneOf struct {
	runtime.Either[MetricMonitorRequest, ErrorMonitorRequest]
}

func (c *CreateMonitorBody_OneOf) Validate() error {
	if c.IsA() {
		if v, ok := any(c.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if c.IsB() {
		if v, ok := any(c.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type UpdateMonitorBody_OneOf struct {
	runtime.Either[MetricMonitorRequest, ErrorMonitorRequest]
}

func (u *UpdateMonitorBody_OneOf) Validate() error {
	if u.IsA() {
		if v, ok := any(u.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if u.IsB() {
		if v, ok := any(u.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}
